### PR TITLE
Standardize timestamps to mitigate the plugin crash.

### LINKED ISSUE #29: Timestamps in event other than `@timestamp` will cause the plugin to crash
Running the following pipeline will cause the codec to crash:

```
input { stdin {}} 
filter { ruby { code => "event.set('[logstash_timestamp]', Time.now());" } } 
output { stdout { codec => fluent  }}
```

with the following error:

```
[2023-01-26T16:34:50,400][ERROR][logstash.javapipeline    ][main] Pipeline worker error, the pipeline will be stopped {:pipeline_id=>"main", :error=>"(NoMethodError) undefined method `to_msgpack' for 2023-01-26T21:34:50.384Z:LogStash::Timestamp", :exception=>Java::OrgJrubyExceptions::NoMethodError, :backtrace=>["org.msgpack.jruby.Packer.write(org/msgpack/jruby/Packer.java:128)"
```

### PR DESCRIPTION
**Pull request by mashhurs**
## What this PR does?
When sending `LogStash::Timestamp` objects to `fluentd`, it raises `undefined method to_msgpack` exception and plugin crashes. This change introduces to standardize the time objects if event contains and then sends to process the encoding.

- Closes #29 

- Test config
```
input {
  stdin {}
}
filter {
  ruby { code => "event.set('[logstash_timestamp]', Time.now());" }
}
output {
 stdout { codec => fluent }
}
```

- Test logs
```
testing
??log?d{?event??original?testing?host??hostname?Mashhurs-MacBook-Pro.local?@version?1?logstash_timestamp?2023-03-21T09:42:10.001294Z?@timestamp?2023-03-21T09:42:09.890141Z?message?testing
hi
??log?d|!??event??original?hi?host??hostname?Mashhurs-MacBook-Pro.local?@version?1?logstash_timestamp?2023-03-21T09:42:57.873664Z?@timestamp?2023-03-21T09:42:57.764443Z?message?hi

```

### CODE REVIEW

File: lib/logstash/codecs/fluent.rb [hunk 1]
```diff
@@ -145,4 +148,10 @@ def generate_event(map, fluent_time, tag)
     event
   end
 
+  def map_timestamp(event_hash)
+    event_hash.each do |k, v|
```
Comment (robbavey) [inline lib/logstash/codecs/fluent.rb:152]: Unfortunately this only works for top level timestamp fields, something like

```
filter {
  ruby { code => "event.set('[logstash][timestamp]', Time.now());" }
}
```

would still fail in the same way

**Review by robbavey — CHANGES_REQUESTED** [review]

File: lib/logstash/codecs/fluent.rb (hunk 1 above)
Comment (mashhurs) [reply lib/logstash/codecs/fluent.rb:152]: Ah, thanks for catching out. I thought `LogStash::Util.normalize(event.to_hash)` L77 will flat the structure. Fixed with [this commit](https://github.com/logstash-plugins/logstash-codec-fluent/pull/30/commits/aba794f699094872e5dbc26ca2ad8c2aa2aca16c).

File: lib/logstash/codecs/fluent.rb [hunk 2]
```diff
@@ -145,4 +148,11 @@ def generate_event(map, fluent_time, tag)
...
+      event_hash[k] = v.to_iso8601 if v.kind_of?(LogStash::Timestamp)
+      event_hash[k] = map_timestamp(v) if v.kind_of?(Hash)
```
Comment (robbavey) [inline lib/logstash/codecs/fluent.rb:154]: Sorry, I should have been more specific - this will still fail if the `LogStash::Timestamp` is in an array as well as a hash - the solution will need to check inside arrays and hashes

Comment (mashhurs) [reply lib/logstash/codecs/fluent.rb:154]: :disappointed_relieved:
Thanks for catch up! Now `Array` is also supported.
Do we have any other structure which can bring crash possibility?

File: lib/logstash/codecs/fluent.rb [hunk 3]
```diff
@@ -145,4 +148,14 @@ def generate_event(map, fluent_time, tag)
     event
   end
 
+  def map_timestamp(event_hash)
```
Comment (robbavey) [inline lib/logstash/codecs/fluent.rb:151]: There is still an issue with complex events that may have multiple hierarchies, and the arrays will also need to be recursed in the same way the hashes are. 

Given [this comment](https://github.com/logstash-plugins/logstash-codec-fluent/pull/30/files#diff-46e627c46cbd94c095fec7ceca988ead0ed7d15c52c170134906f862227d7409R80) about not mutating the original data, maybe we could implement `map_timestamp` like this?

```suggestion
  def normalize_timestamps(o)
    case o
    when Hash
      o.inject({}){|c, (k, v)| c[k] = map_timestamp(v); c}
    when Array
      o.map{|i| map_timestamp(i)}
    when LogStash::Timestamp
      o.to_iso8601
    else
      o
    end
  end
```
  In which case, our `@on_event.call` method would look like:

```
@on_event.call(event, @packer.pack([tag, epochtime, normalize_timestamps(data)]))
```

Comment (mashhurs) [reply lib/logstash/codecs/fluent.rb]: I believe with your suggestion we need to opt out the `map_timestamp` method and pushed with [this commit](https://github.com/logstash-plugins/logstash-codec-fluent/pull/30/commits/e0d7a0e5948d94fb5d5c76f7d8af6de73ac66621).

File: CHANGELOG.md [hunk 4]
```diff
@@ -1,3 +1,6 @@
+## 3.4.2
+  - Fix: timestamp values are converted to iso-8601 to resolve the crash [#30](https://github.com/logstash-plugins/logstash-codec-fluent/pull/30)
```
Comment (robbavey) [inline CHANGELOG.md:2]:
```suggestion
  - Fix: Convert LogStash::Timestamp values to iso-8601 to resolve crash issue with `msgpack` serialization [#30](https://github.com/logstash-plugins/logstash-codec-fluent/pull/30)
```

**Review by robbavey — APPROVED** [review]
Code looks good, left suggestion on changelog comment
